
services:
  test:
    build: .
    command: npm run test
    environment:
      - NODE_ENV=test
      - PORT=3000
      - IS_LOCAL=true
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - REMINDER_LEAD_MINUTES=30
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_started
      test-setup:
        condition: service_completed_successfully

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5

  dynamodb:
    image: amazon/dynamodb-local:2.6.1
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - dynamodb-test-data:/home/dynamodblocal

  test-setup:
    build: .
    command: sh -c "npm run create-tables && npm run test:setup"
    environment:
      - NODE_ENV=test
      - IS_LOCAL=true
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

volumes:
  dynamodb-test-data: